[package]
name = "nyaterm-transport"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
async-http-proxy.workspace = true
base64.workspace = true
dirs.workspace = true
encoding_rs.workspace = true
flate2 = { version = "1", default-features = false, features = ["rust_backend"] }
futures.workspace = true
md5.workspace = true
portable-pty.workspace = true
regex.workspace = true
russh.workspace = true
russh-sftp.workspace = true
serialport.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tracing.workspace = true
time.workspace = true
tokio.workspace = true
tokio-socks.workspace = true
uuid.workspace = true
zeroize.workspace = true
zmodem2.workspace = true
