[package]
name = "nyaterm-vnc-helper"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "nyaterm-vnc-helper"
path = "src/main.rs"

[dependencies]
nyaterm-remote-desktop.workspace = true
tokio.workspace = true
vnc.workspace = true
zeroize.workspace = true
