[package]
name = "nyaterm-desktop"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
dirs.workspace = true
encoding_rs.workspace = true
futures.workspace = true
gpui.workspace = true
hex.workspace = true
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "gif", "bmp", "webp"] }
keyring.workspace = true
md5.workspace = true
nyaterm-core.workspace = true
nyaterm-otp.workspace = true
nyaterm-remote-desktop.workspace = true
nyaterm-store.workspace = true
nyaterm-terminal.workspace = true
nyaterm-terminal-gpui.workspace = true
nyaterm-transport.workspace = true
nyaterm-ui.workspace = true
regex.workspace = true
rust-i18n.workspace = true
rand.workspace = true
quick-xml.workspace = true
rqrr = "0.9"
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
time.workspace = true
tracing.workspace = true
zed_reqwest.workspace = true
zip.workspace = true
zeroize.workspace = true

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_System_DataExchange",
    "Win32_System_Ole",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
] }
